version: "3.5"
services:
  web_app:
    image: python-flask_web_dev:latest
    build: .
    ports:
     - "4000:4000"
    volumes:
     - .:/app
    environment:
     - ENV=development
     - PORT=4000
     - DB=mongodb://mongodb:27017/AATF
     - SECRET=MOUATTAMAHDI
  app:
    image: elko95/aatf2-app:latest
    ports:
      - "3001:3001"
    links:
      - mongodb
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/AATF
      - PORT=3001
      - JWT_SECRET=MOUATTAMAHDI
  mongodb:
    image: mongo:4.0
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/usr/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/usr/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  client:
    image: tinashe12/docker-autobuild-app
    build: .
    ports:
      - "3000:80"
    environment:
      CLIENT_HOST: 157.245.88.152 # This is the address of the react client
